
version: '3.3'

services:

  db:
    build: db
    image: db
    container_name: db


  words:
    build: back
    image: back
    container_name: back
    ports:
    - 8080:8080

  front:
    build: front
    image: front
    ports:
    - 80:80