name : Front Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{github.repository}}
      ACTOR: ${{github.actor}}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: downcase
      run: |
       echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
       echo "ACTOR=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name : Build and push
      uses : docker/build-push-action@v4
      with:
       context: front
       push: true 
       tags: ${{env.REGISTRY}}/${{env.ACTOR}}/${{env.IMAGE_NAME}}-front:1.0.
