name : Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{github.repository}}
      ACTOR: ${{github.actor}}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - uses: dorny/path-filter@v2
      id: changes
      with: 
        filters: |
        back
        - 'back/**'
        front
        - 'front/**'
          db
        - 'db/**'

    - name: downcase
      run: |
       echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
       echo "ACTOR=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ env.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name : Build and push
      if: steps.changes.outputs.back == 'true'
      uses : docker/build-push-action@v4
      with:
       context: back
       push: true 
       tags: ${{env.REGISTRY}}/${{env.ACTOR}}/${{env.IMAGE_NAME}}-back:1.0.

    - name : Build and push
      if: steps.changes.outputs.back == 'true'
      uses : docker/build-push-action@v4
      with:
       context: front
       push: true 
       tags: ${{env.REGISTRY}}/${{env.ACTOR}}/${{env.IMAGE_NAME}}-front:1.0.
       
    - name : Build and push
      if: steps.changes.outputs.db == 'true'
      uses : docker/build-push-action@v4
      with:
       context: db
       push: true 
       tags: ${{env.REGISTRY}}/${{env.ACTOR}}/${{env.IMAGE_NAME}}-db:1.0.
